version: '3.3'

services:

  
  opentts:
    image: synesthesiam/opentts:hi
    user: root
    ports:
      - 5500:5500  
    expose:
      - 5500
    networks:
      - api-network

      
  tiles:
    build: ./
    command: sh /app/entrypoint.sh
    # command: uvicorn main:app --host 0.0.0.0 --port 8000
    # command: "tail -F anything"
    restart: unless-stopped
    ports:
      - 8080:8080
    expose:
      - 8080
    container_name: tilesdemo
    networks:
      - api-network
    environment:
      - RESPONSETSV=/app/data/answers_climate_hin.tsv
      - RHASSPY_URL=http://rhasspy:12101
      - AUDIODIR=/app/audio
      - FALLBACKAUDIOPATH=/app/data/GV_fallback_hin_climate_v2.mp3
      - COMPLETIONAUDIOPATH=/app/data/GV_completion_hin_climate.mp3
      - SKIPAUDIOPLAY=0
      - TTSFALLBACK=0
    devices:
        - "/dev/snd:/dev/snd"
    volumes: 
      - ./:/app
      - ../TILES-audio:/app/audio
      - ./applog.log:/app/applog.log

    depends_on:
      - rhasspy

  rhasspy:
    image: "rhasspy/rhasspy"
    container_name: rhasspy
    restart: unless-stopped
    volumes:
        - "$HOME/.config/rhasspy/profiles:/profiles"
        - "/etc/localtime:/etc/localtime:ro"
    expose: 
        - 12101
    ports:
        - "12101:12101"
    devices:
        - "/dev/snd:/dev/snd"
    command: --user-profiles /profiles --profile hi
    networks: 
      - api-network
    
    
networks:
  api-network:
    external: true
      
      
  


